class DataIngestionArtifact:...
class DataValidationArtifact:...
class DataTransformationArtifact:...
class ModelTrainerArtifactArtifact:...
class ModelEvalutionArtifact:...
class ModelPusherArtifact:...